### ISSUE TITLE
Make airtime a public property and split trackAirtime into calculateAirtime

### ISSUE THREAD

**Issue by amkuipers** [TheThingsNetwork/arduino-device-lib#160]
In v1.0, `sendBytes` updates private airtime in class `TheThingsNetwork`. In beta, examples just send data and delay for 20s or so. In production there is a need for users to control airtime, and it would be great if the library supports it. I am not aware if TTN Uno has a RTC to 'reset daily used airtime'. But some assistance in calculating a delay/sleep would help. 
Example`: delay_ms = calc_delay( sizeof (user_data_upstream) + sizeof (user_data_downstream ))`, that uses the private `fp` and `sf`, etc, to calculate the minimum delay. 
If an RTC is available, the used airtime can be recorded per day, and the `calc_delay()` can use the remaining airtime in the calculation. 
Documentation then can have examples that use that delay, or less; multiply the delay by 2, or use something like `max( calc_delay(..), SIX_HOUR)`.

**Comment by FokkeZB** [comment]
I suggest we:

- [ ] Make [`float airtime`](https://github.com/TheThingsNetwork/arduino-device-lib/blob/master/src/TheThingsNetwork.h#L45) public so that users can programmatically retrieve the total airtime to make informed decisions, e.g. to change delays. It also enables them to reset the airtime to `0`, e.g. every 24h.
- [ ] Split [`trackAirtime()`](https://github.com/TheThingsNetwork/arduino-device-lib/blob/master/src/TheThingsNetwork.cpp#L518-L527) to create separate public `calculateAirtime()` method to allow users to calculate how much a message will cost before sending it.

**Comment by johanstokking** [comment]
@FokkeZB agreed

**Comment by FokkeZB** [comment]
Closed by #162
